import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { reports } from "@/lib/catalog-data";
import { intelligenceEvents } from "@/lib/intelligence-data";

export function generateStaticParams(){return reports.map(i=>({slug:i.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const r=reports.find(i=>i.slug===slug);return{title:r?.title??"研究报告",description:r?.summary}}
export default async function ReportDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const report=reports.find(i=>i.slug===slug);if(!report)notFound();return <main className="page-shell subpage printable"><header className="report-hero"><p className="eyebrow">{report.type} · {report.date}</p><h1>{report.title}</h1><p>{report.summary}</p><div>{report.tags.map(t=><span key={t}>{t}</span>)}<span>{report.sources} 个来源</span></div></header><article className="report-body"><Section title="摘要"><p>{report.summary} 本报告只使用当前快照中可回溯的事实，未披露金额与推测性结论不进入统计。</p></Section><Section title="核心观点"><ol><li>不同披露口径必须拆分，不能机械相加。</li><li>技术发布、融资完成和基础设施承诺是不同类型事件。</li><li>样本完整度决定结论边界，缺失不是零。</li></ol></Section><Section title="事实与数据"><div className="timeline">{intelligenceEvents.slice(0,5).map(e=><div key={e.id}><time>{e.publishedAt}</time><div><strong>{e.title}</strong><p>{e.summary}</p><a href={e.source.url} target="_blank" rel="noreferrer">{e.source.name}</a></div></div>)}</div></Section><Section title="方法与口径"><p>来源优先级依次为监管与交易所、公司和机构官网、人物原始材料、权威媒体。事件按规范化 URL、标题、日期、公司、金额与投资方组合去重。</p></Section><Section title="风险与反证"><p>当前样本对主动披露的大型企业存在偏倚；不同市场的信息时效、币种和监管口径不一致。任何热度或事件计数都不应直接解释为未来回报。</p></Section><Section title="后续跟踪"><ul><li>增量同步官方 RSS 与监管文件。</li><li>补齐公司别名和跨语言实体消歧。</li><li>保存来源冲突与历史修订。</li></ul></Section><footer>修订时间：2026-07-24 · 本文不构成投资建议</footer></article></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><p className="section-index">{title}</p><h2>{title}</h2>{children}</section>}
