import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { companies, institutionCatalog } from "@/lib/catalog-data";

export function generateStaticParams(){return institutionCatalog.map(i=>({slug:i.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;return{title:institutionCatalog.find(i=>i.slug===slug)?.name??"机构档案"}}
export default async function InstitutionDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const item=institutionCatalog.find(i=>i.slug===slug);if(!item)notFound();const related=companies.filter(c=>item.sectors.some(s=>c.sector.includes(s)||s.includes("科技"))).slice(0,8);return <main className="page-shell subpage"><header className="entity-hero"><div><p className="eyebrow">{item.region} · {item.type}</p><h1>{item.name}</h1><p>{item.englishName}</p><div className="hero-chips"><span>{item.stages}</span>{item.sectors.map(s=><span key={s}>{s}</span>)}</div></div><div className="entity-monogram">{item.name.slice(0,2).toUpperCase()}</div></header><div className="detail-layout"><aside className="toc"><strong>机构档案</strong>{["投资偏好","代表性样本","近期方向","退出与IRR","来源"].map(i=><a href={`#${i}`} key={i}>{i}</a>)}</aside><article className="detail-article"><Section id="投资偏好" title="公开投资偏好"><dl className="facts-grid"><div><dt>机构类型</dt><dd>{item.type}</dd></div><div><dt>投资阶段</dt><dd>{item.stages}</dd></div><div><dt>地域</dt><dd>{item.region}</dd></div><div><dt>管理规模</dt><dd>N/A · 未纳入核验</dd></div></dl><div className="chip-list">{item.sectors.map(s=><span key={s}>{s}</span>)}</div></Section><Section id="代表性样本" title="同偏好赛道公司"><p className="data-note">以下仅按赛道标签匹配，不等同于该机构已经投资。</p><div className="entity-list">{related.map(c=><Link href={`/companies/${c.slug}`} key={c.slug}><strong>{c.name}</strong><span>{c.region} · {c.product}</span></Link>)}</div></Section><Section id="近期方向" title="近 90 天方向变化"><p className="data-note">需要逐笔投资事件和历史基线后才能计算。当前不以静态官网投资组合推断策略变化。</p></Section><Section id="退出与IRR" title="公开退出与 IRR"><p>机构整体 IRR：N/A。本站不使用少量公开退出案例估算机构整体回报。</p></Section><Section id="来源" title="原始来源"><a className="source-card" href={item.source.url} target="_blank" rel="noreferrer"><span>{item.source.level}</span><strong>{item.source.name}</strong><small>{item.source.url}</small></a></Section></article><aside className="source-rail"><div className="confidence-box"><span>资料状态</span><strong>部分数据</strong><p>官网级基础资料已核验；投资事件将由同步任务增量补充。</p></div></aside></div></main>}
function Section({id,title,children}:{id:string;title:string;children:React.ReactNode}){return <section id={id} className="article-section"><p className="section-index">{id}</p><h2>{title}</h2>{children}</section>}
