"""Create all core intelligence tables.

Revision ID: 0001
Revises:
"""
from backend.app.models import Base

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The model metadata is the single typed definition for the initial 25-table schema.
    # Later revisions use explicit operations generated by Alembic autogenerate.
    Base.metadata.create_all(bind=op.get_bind())
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
